'use client'


import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }


import { usePathname } from "next/navigation";
export default function Layout({ children }) {
  const pathName = usePathname()
  if (pathName.startsWith('/admin')) {
    return <html lang="en" data-theme="light" > 
      <body>
        {children}
      </body>
    </html>
  }
  return (
   <html lang="en" data-theme="light">
    <body>
    <div>
      {children}
    </div>
    </body>
   </html>
  );
}
